### ISSUE TITLE
Wrong unit for vertical_velocity in documentation of advect_level

### ISSUE THREAD

**Issue by depion** [contrailcirrus/pycontrails#102]
**Description**

I think the documentation of `advect_level` states the wrong unit for the argument `vertical_velocity`, which should be Pa/s instead of m/s.

https://github.com/contrailcirrus/pycontrails/blob/main/pycontrails/physics/geo.py#L822

Compare:

https://github.com/contrailcirrus/pycontrails/blob/d574d9d28367e847fa3565e80de35c2b369446b6/tests/benchmark/cocip/data.md?plain=1#L242

**Details**

- Version: 0.47.2

**Comment by zebengberg** [comment]
Thanks @depion ! I fixed this in a2fa351594106d92fa9286d787a7e16d3517034a
