### ISSUE TITLE
Minor pain points in develop instructions

### ISSUE THREAD

**Issue by thabbott** [contrailcirrus/pycontrails#142]
I ran into a few minor pain points while following instructions for creating a pycontrails development environment (https://py.contrails.org/develop.html). I'm documenting them here in case the record is useful. Addressing them might somewhat improve the new-developer experience, but probably shouldn't be a priority.

- "Copy to clipboard" buttons copy a leading `$`. (This is true throughout the online documentation.) 
- I couldn't clone the pycontrails repository via SSH, probably because I don't have an SSH key set up. git's error message isn't very informative, though, so it may be worth adding a note about setting up SSH keys (https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent) or about cloning via HTTPS.
- Some tests require a CDS API key (https://cds.climate.copernicus.eu/api-how-to) and/or access to GCP storage buckets. Possibly worth noting these requirements so users aren't surprised when some tests fail.

**Comment by mlshapiro** [comment]
>"Copy to clipboard" buttons copy a leading $. (This is true throughout the online documentation.)

Please configure [this option](https://sphinx-copybutton.readthedocs.io/en/latest/use.html#strip-and-configure-input-prompts-for-code-cells) in [conf.py](https://github.com/contrailcirrus/pycontrails/blob/main/docs/conf.py)

> I couldn't clone the pycontrails repository via SSH

I agree with adding a note and link to the Github SSH docs!

> Some tests require a CDS API key

Most of these tests should be skipped if the GCP access is not set up. Can you try to intelligently skip the tests that require credentials that may not exist? 

You can [skip the test with a decorator](https://github.com/contrailcirrus/pycontrails/blob/bfae7745ea142340e3a1c0cbbf066ae4579b4e57/tests/unit/test_cache.py#L149) and if necessary define relevant fixtures in [conftest](https://github.com/contrailcirrus/pycontrails/blob/main/tests/unit/conftest.py).

**Comment by thabbott** [comment]
> Please configure [this option](https://sphinx-copybutton.readthedocs.io/en/latest/use.html#strip-and-configure-input-prompts-for-code-cells) in [conf.py](https://github.com/contrailcirrus/pycontrails/blob/main/docs/conf.py)

👍 

> I agree with adding a note and link to the Github SSH docs! Source for docs is in in the [/docs](https://github.com/contrailcirrus/pycontrails/tree/main/docs) directory

👍 

> Most of these tests should be skipped if CDS / GCP access is not set up. Can you try to intelligently skip the tests that require credentials that may not exist?

I wasn't very clear about some of the testing issues. The CDS-related error I ran into came from the the testing harness, not any specific test. Without a `.cdsapirc` file, running `make test` produces an error because of the dependency on `ensure_era5_cached` (via `nb-test`). I'll think some more about a solution.

I haven't been able to reproduce the GCP-related test errors I was getting. Some tests in the `TestGCPCacheStore` suite ([test_cache.py](https://github.com/contrailcirrus/pycontrails/blob/main/tests/unit/test_cache.py)) were failing while I was in the process of setting up GCP credentials. I tried revoking my credentials and the tests were skipped, and I re-enabled them and the tests passed. So, not sure why I was having trouble before...
