### ISSUE TITLE
Sync and review `climaccf` fork

### ISSUE THREAD

**Issue by mlshapiro** [contrailcirrus/pycontrails#143]
**Description**

Previously the [dlr-pa/climaccf](https://github.com/dlr-pa/climaccf) repository would only work on older versions of Python. We chose to fork the repository to [contrailcirrus/climaccf](https://github.com/contrailcirrus/climaccf) to create the example [ACCF.ipynb](https://py.contrails.org/examples/ACCF.html).

The origin repository has since been updated and we should investigate if we need this fork anymore.

**Additional context**

This will be relevant to CICONIA.

**Comment by trdean1** [comment]
Updated [contrailcirrus/climaccf](https://github.com/contrailcirrus/climaccf) to reflect the latest changes from [dlr-pa/climaccf](https://github.com/dlr-pa/climaccf).  Unfortunately [dlr-pa/climaccf](https://github.com/dlr-pa/climaccf) still pins to an older version of numpy so our fork is still needed for now
