### ISSUE TITLE
Suggestion to change name of the "MIT ash" scheme to the "SEVIRI ash" scheme

### ISSUE THREAD

**Issue by VincentMeijer** [contrailcirrus/pycontrails#168]
Concerns the "MIT ash" RGB product, referenced in the function:
https://github.com/contrailcirrus/pycontrails/blob/d5cb93cf3a70dd2e2301fe82529c52b4fc124133/pycontrails/datalib/goes.py#L675.

The recipe for the particular ash RGB used in the Kulik (2019) thesis is based on the [SEVIRI ash recipe](https://resources.eumetrain.org/data/4/410/navmenu.php?tab=5&page=2.0.0), I believe. The linked resource also has some nice examples of interpretation of the ash RGB.

Perhaps it makes sense to replace the citation to the MIT Thesis with this one, or at least add it?

**Comment by mlshapiro** [comment]
@VincentMeijer just pulled this into the main, thanks for the suggestion!
