### ISSUE TITLE
Run `nbval` in stricter mode

### ISSUE THREAD

**Issue by zebengberg** [contrailcirrus/pycontrails#18]
- Run notebook tests as part of the CI. This could happen when a pull request is opened.
- Right now, `nbval-lax` is run. We may want to run the stricter `nbval` check (no lax).
- Consider using a tool like [nb-clean](https://github.com/srstevenson/nb-clean) to sanitize notebooks. This can be used with pre-commit.

**Comment by mlshapiro** [comment]
As part of this task, lets try to add back in the changes reverted in 8266a852720c7e92fa6670c32088fab8abf35c31. It would be great if the notebooks executed in the Action before being built into the docs.

The `skip-execution` tag can be added to any cells that shouldn't be run at that time.
