### ISSUE TITLE
RuntimeWarning: Engine 'cfgrib' loading failed

### ISSUE THREAD

**Issue by Calebsakhtar** [contrailcirrus/pycontrails#196]
**Description**
Performing the installation `python -m pip install "pycontrails[complete]"` and running the example "Run CoCiP over a flight" ([https://py.contrails.org/notebooks/run-cocip-on-flight.html](https://py.contrails.org/notebooks/run-cocip-on-flight.html)) results in the following runtime warning:

`RuntimeWarning: Engine 'cfgrib' loading failed: Cannot find the ecCodes library warnings.warn(f"Engine {name!r} loading failed:\n{ex}", RuntimeWarning)` 

**Details**
- Version: pycontrails 0.51.0
- Module: N/A
- OS: Windows

**Steps to Reproduce**
1. Create an anaconda environment: `conda create --name pycontrails`
2. Activate the anaconda environment: `conda activate pycontrails`
3. Install Python 3.9 to the environment: `conda install python==3.9`
4. Install pycontrails using pip: `python -m pip install "pycontrails[complete]"`
5. Run the example from the following link: [https://py.contrails.org/notebooks/run-cocip-on-flight.html](https://py.contrails.org/notebooks/run-cocip-on-flight.html)

**Additional Notes**
I have been able to eliminate this warning by running `python -m pip install ecmwflibs`. This solution was obtained here, but does not seem to be universal: [https://github.com/ecmwf/eccodes-python/issues/54#issuecomment-925036724](https://github.com/ecmwf/eccodes-python/issues/54#issuecomment-925036724)

**Comment by thabbott** [comment]
Have you tested your eccodes installation with `python -m eccodes selfcheck`? If not, then I'd start with that to confirm that your environment can find the eccodes libraries. If you don't have them installed, you can install them using conda: see https://pypi.org/project/eccodes/.

All of that said, I've seen that warning before and it hasn't stopped me from running CoCiP. Unless you're having other issues that you think are connected to this warning you're probably safe to ignore it.

**Comment by Calebsakhtar** [comment]
Thanks for your insight and quick response @thabbott. I did perform the test for my `eccodes` installation. The check could not find `eccodes` before running `python -m pip install ecmwflibs`, but did find it after running the command.

I was just worried the CoCiP results could be affected, but it doesn't seem to be the case. I leave it up to you whether you want to close this issue or leave it open.

**Comment by mlshapiro** [comment]
@Calebsakhtar I took a closer look at this issue. Unfortunately `ecmwflibs` is a bit outdated and doesn't exist for Python 3.12.

I'm going to close this issue with the resolution that installing `ecmwflibs` on older versions of Python can help solve `eecodes` install issues.

**Comment by Brian75321** [comment]
Hello,

I am getting this error when I try to run the "Run CoCiP over a flight" notebook tutorial:

c:\Users\m317386\.venv\Lib\site-packages\xarray\backends\plugins.py:110: RuntimeWarning: Engine 'cfgrib' loading failed:
Cannot find the ecCodes library
  external_backend_entrypoints = backends_dict_from_pkg(entrypoints_unique)


SPECIFICATIONS:
----------------
PyContrails 0.54.5
Windows 11
Python 3.13.1
Pip install "pycontrails[complete]"
git clone https://github.com/contrailcirrus/pycontrails.git
.venv
----------------

Even with that error, I am still able to access the met data and run CoCiP. **But the error message is troubling.**

When I try:   python -m pip install ecmwflibs, I get the following error message:

ERROR: Could not find a version that satisfies the requirement ecmwflibs (from versions: none)
ERROR: No matching distribution found for ecmwflibs

When I try pip install "pycontrails[ecmwflibs]", it indicates:

C:\Users\m317386\.venv>pip install "pycontrails[ecmwflibs]"
Requirement already satisfied: pycontrails[ecmwflibs] in c:\users\m317386\.venv\lib\site-packages (0.54.5)
WARNING: pycontrails 0.54.5 does not provide the extra 'ecmwflibs'
Requirement already satisfied: dask>=2022.3 in c:\users\m317386\.venv\lib\site-packages (from pycontrails[ecmwflibs]) (2024.12.1)
Requirement already satisfied: numpy>=1.22 in c:\users\m317386\.venv\lib\site-packages (from pycontrails[ecmwflibs]) (2.2.1)
Requirement already satisfied: pandas>=2.2 in c:\users\m317386\.venv\lib\site-packages (from pycontrails[ecmwflibs]) (2.2.3)
etc.

Please help.

**Comment by zebengberg** [comment]
@Brian75321 

I think this warning is completely benign unless you're make use of grib files. Like you pointed out, this is intertwined with `ecmwflibs` not building recent wheels (there are [many issues](https://github.com/ecmwf/ecmwflibs/issues) describing this). You may be able to avoid the warning if you run with python 3.11.

In the meantime, I can look into tweaking the dependencies to no longer require anything touching `cfgrib`.

**Comment by Brian75321** [comment]
Understood.  I will try using python 3.11 and will ignore any error messages if they persist.
This error did not occur on another computer where I had Anaconda installed and installed PyContrails using conda. I believe it had Python 3.12 (or 3.13)

This error only seems to occur when I install Python directly and install PyContrails with PiP.
Appreciate if you could tweak the dependencies.
Thank you!

**Comment by zebengberg** [comment]
@Brian75321 

ECMWF released [eccodes 2.39.2](https://pypi.org/project/eccodes/2.39.2/) which contains 3.13 wheels. I believe you'll be able to get the warning to go away if you update your dependencies.

**Comment by Brian75321** [comment]
Thank you!
