### ISSUE TITLE
NAN in in edb-gaseous-v29b-engines.csv

### ISSUE THREAD

**Issue by depion** [contrailcirrus/pycontrails#215]
**Description**

In the table https://github.com/contrailcirrus/pycontrails/blob/98008ed98690f62d72027596cf23a5930c9a7c61/pycontrails/models/emissions/static/edb-gaseous-v29b-engines.csv there is an entry for UID 1ZM001 which has no entry/nan for `Fuel Flow Idle (kg/sec)
`.  This leads to a problem if the `EmissionsProfileInterpolator` is applied to this data, finally raising an exception here: https://github.com/contrailcirrus/pycontrails/blob/main/pycontrails/core/interpolation.py#L674

**Details**

- Version: pycontrails[complete]==0.50.2

**Comment by roger-teoh** [comment]
Hi Dennis, thank you for spotting this error! I had a look at it and can confirm that the value is also missing in the original ICAO EDB v29b dataset. 

In all previous versions, we typically remove engines that contain missing fuel mass flow rate values. However, for this case, given that the engine characteristics of `1ZM001` is completely identical to `13ZM002`, I have implemented a simple fix by filling the missing `Fuel Flow Idle (kg/sec)` value with those provided by the `13ZM002` engine. This minor change will be merged into the pycontrails repository pending approval from @mlshapiro

**Comment by mlshapiro** [comment]
Merged - this will get pushed to pypi on the next release, but available if you pull main!
