### ISSUE TITLE
Remove Aircraft class and document special Flight.attr keys

### ISSUE THREAD

**Issue by depion** [contrailcirrus/pycontrails#36]
**Description**

I struggle to understand the difference between `engine_uid` and `engine_name`. According to the documentation, the `Aircraft` class contains the attribute `engine_name`. The `Flight` class contains nothing related to the engine itself, only an unspecified `attrs` attribute. 

https://py.contrails.earth/api/pycontrails.Aircraft.html
https://py.contrails.earth/api/pycontrails.Flight.html

Internally, I find that `engine_uid` is used for BADA4 support. 

https://github.com/contrailcirrus/pycontrails-bada/blob/32ce4a5544929fcf78f490bc353ae74c965929d9/pycontrails_bada/bada_interface.py#L124

In `BADAFlight.eval` the docstring says

```
If the following variables are not provided in the flight attribute, the default aircraft-engine assignment and
aircraft mass properties from BADA will be assumed:
- engine_uid
```

https://github.com/contrailcirrus/pycontrails-bada/blob/4968c976cd2b35efc94b134f49d7c201c6f60df2/pycontrails_bada/bada_model.py#L396

So, `engine_uid` should be given in the `Flight.attrs` dictionary? What is `Aircraft.engine_name` used for? Maybe some documentation is lacking on the usage and the differences?

**Comment by mlshapiro** [comment]
@depion thanks for requesting the clarification, and this is obviously confusing. 

We had designed the `Aircraft` class to define aircraft attributes in a consistent way (with a dataclass) but we never finished the feature -- therefore, the `Aircraft` class currently is not used.

The flight `attrs` is just a plain Python dict. We use this to specify flight and aircraft attributes, including `engine_name` and `engine_uid`.  So you are correct, `engine_uid` should be given in the `Flight.attrs` dictionary.

@roger-teoh can you please post the difference between `engine_name`  and `engine_uid`. From what I remember, the `engine_name` is the common name and `engine_uid` is the reference to the engine within the ICAO Emissions databank.

This needs to be better documented, so thank you for bringing it up.

This is also a good moment to decide if we should finish implementing the `Aircraft` class to make data input clearer.

**Comment by roger-teoh** [comment]
@depion engine_uid is the "unique identification number for an ICAO Aircraft EDB entry", while engine_name is the long name. For example, the CFM "LEAP-1A26/26E1" is the engine name, while the engine_uid in the ICAO EDB is "01P20CM128".

**Comment by mlshapiro** [comment]
As part of this, we should demote `fuel` from being a Flight property and make it an attribute, like everything else.

We can consider creating a FlightAttrs dataclass with all these keys that gets validated on Flight init. There are cost/benefits to this.
