### ISSUE TITLE
Better Cartopy support

### ISSUE THREAD

**Issue by trdean1** [contrailcirrus/pycontrails#46]
**Description**

Cartopy is a pain to get work correctly with the other pycontrails dependencies.  Provide an optional install target that installs a working version of cartopy, e.g. `pip install pycontrails[cartopy]`

**Comment by zebengberg** [comment]
Cartopy 0.22 has removed the GEOS system dependency, so `pip install cartopy` (hopefully) just works. Cartopy is also included with `pip install pycontrails[goes]`.
