### ISSUE TITLE
Determine appropriate interpolation methodology for pressure level and specific humidity

### ISSUE THREAD

**Issue by mlshapiro** [contrailcirrus/pycontrails#61]
**Description**

In discussions with collaborators, we've received the suggestion to interpolate pressure levels on a log scale to better approximate geometric altitude.

We've also heard the recommendation to interpolate specific humidity as the log(specific humidity) to account for the wide range of value.

**Alternatives**

- Linear interpolation (current method)

**Additional context**

Per discussion 

@zebengberg @mccloskey

**Comment by mccloskey** [comment]
[ERA5_RHi_histogram_matching_eckel_transform.ipynb.zip](https://github.com/contrailcirrus/pycontrails/files/11578156/ERA5_RHi_histogram_matching_eckel_transform.ipynb.zip)

Here's an example of determining the histogram matching coefficients and calculating/using eckel coefficients (as reviewed in Wilks 2018) to help sort this out.
