### ISSUE TITLE
Wrong OLR weather value in ACCF contrail

### ISSUE THREAD

**Issue by Reyrem** [contrailcirrus/pycontrails#64]
**Description**

The contrail accf by day is not using the right weather variable for outgoing longwave radiation. Climaccf is using "top net thermal radiation (ttr)" in J m^-2 from ERA5 single level dataset. It is then divided in their implementation by the time interval (3600s in this case) to convert it to the mean flux on this time interval (W m^-2). Climaccf should therefore be given the value in J m^-2, and not the one in W m^-2.

This is the expected result with Climaccf : 
![climaccf_contrailACCF](https://github.com/contrailcirrus/pycontrails/assets/73607302/dce59ae7-9402-48f1-9dc3-138b6681e84b)

This is the result with Pycontrail accf:
![pycontrail_contrailACCF](https://github.com/contrailcirrus/pycontrails/assets/73607302/a5774564-f986-4ab9-9e49-6dabd3f8c33d)

This is the result with climaccf with the wrong OLR values :
![climaccf_contrailACCF_wrong_OLR](https://github.com/contrailcirrus/pycontrails/assets/73607302/5a7b85ec-6b9c-4cf6-adf4-4fb95613d1c4)

We think this is the main difference between the two results.

**Details**

- Version: 		0.42.0
- Module:		models.accf
- OS: 			windows

**Steps to Reproduce**

1. Run the accfs with pycontrail
2. Compare with Climaccf with both the weather variable in J/m-² and in W/m-²

**Comment by mlshapiro** [comment]
This is super helpful, thanks @Reyrem . 

We made the choice to modify the accumulated values on load because it made downstream modeling simpler, but only for the internally built models. I think it was an incorrect choice, so we'll find a way to stop modifying the input meteorology by default.

**Comment by trdean1** [comment]
I just ran across this issue in some comparison work I was doing.  A work around to this would be to multiply by `3600*step_size` after [this line](https://github.com/contrailcirrus/pycontrails/blob/2c1b92fd45e3e24d6b6676c9e0382a9d2df8e483/pycontrails/models/accf.py#L309) in our wrapper code.  

@mlshapiro is there any objection to doing this now and removing it once we change how the met data gets loaded?

**Comment by zebengberg** [comment]
Fixed in #104
