### ISSUE TITLE
Wrong use of constants.epsilon in sac.slope_mixing_line

### ISSUE THREAD

**Issue by Wessel99** [contrailcirrus/pycontrails#72]
**Description**

The sac.slope_mixing_line function is making use of parameter constants.epsilon, but epsilon is placed at an incorrect location in the equation. How constants.epsilon is currently defined (epsilon: float = R_d / R_v), it should be placed above the division bar, not below.

Either epsilon should be redefined as:
epsilon: float = R_v/ R_d

or 

slope_mixing_line should be redefined as:
slope_mixing_line = (ei_h2o * c_pm * air_pressure * constants.epsilon) / (q_fuel * (1.0 - engine_efficiency))

**Details**

- Version: [0.45.0]
- Module: [sac.slope_mixing_line, constants.epsilon]
- OS: [windows]

**Additional Notes**

Current code:

#: Ratio of gas constant for dry air / gas constant for water vapor
epsilon: float = R_d / R_v

def slope_mixing_line(
    specific_humidity: ArrayLike,
    air_pressure: ArrayLike,
    engine_efficiency: float | ArrayLike,
    ei_h2o: float,
    q_fuel: float,
) -> ArrayLike:
    r"""Calculate the slope of the mixing line in a temperature-humidity diagram.

    This quantity is often notated with ``G`` in the literature.

    Parameters
    ----------
    specific_humidity : ArrayLike
        A sequence or array of specific humidity values, [:math:`kg_{H_{2}O} \ kg_{air}`]
    air_pressure : ArrayLike
        A sequence or array of atmospheric pressure values, [:math:`Pa`].
    engine_efficiency: float | ArrayLike
        Engine efficiency, [:math:`0 - 1`]
    ei_h2o : float
        Emission index of water vapor, [:math:`kg \ kg^{-1}`]
    q_fuel : float
        Specific combustion heat of fuel combustion, [:math:`J \ kg^{-1} \ K^{-1}`]

    Returns
    -------
    ArrayLike
        Slope of the mixing line in a temperature-humidity diagram, [:math:`Pa \ K^{-1}`]
    """
    c_pm = thermo.c_pm(specific_humidity)  # Often taken as 1004 (= constants.c_pd)
    return (ei_h2o * c_pm * air_pressure) / (constants.epsilon * q_fuel * (1.0 - engine_efficiency))

**Comment by zebengberg** [comment]
Thanks for looking into this!

Do you have a reference for your proposed formula? [Schumann 1996](https://elib.dlr.de/32128/1/mz-96.pdf) gives `epsilon = 0.622` in the text between display (6) and (7). This agrees with the pycontrails value. Moreover, the formula for `G` in display (8) is consistent with the implementation here.

Thanks!

**Comment by Wessel99** [comment]
Hi!

You are right! I went back to my references ([https://www.annualreviews.org/doi/pdf/10.1146/annurev-fluid-010814-013619](Paoli 2016) and an old university lecture), and is seems that they both got it backwards by coincedence. 

Sorry for the confusion.

Cheers!

**Comment by zebengberg** [comment]
No worries! Thanks for checking. Let us know if you see other discrepancies.
