### ISSUE TITLE
GFS + PCR differs widely from ERA5 + PCR

### ISSUE THREAD

**Issue by Cybis320** [contrailcirrus/pycontrails#74]
**Description**

I'm sure I missed something, and I don't yet understand humidity scaling but something looks off using ISSR and PCR with GFS:

- Running SAC on both GFS and ERA5 metdataset -> essentially identical results.
- Running ISSR on both sets with specifying humidity scaling -> essentially identical results
- Running ISSR on both sets without specifying humidity scaling -> widely different results
- Running PCR (which doesn't allow for specifying humidity scaling afaik) -> widely different results

What am I missing?

**Details**

- Version: [ 0.45]
- Module: [issr.py, pcr.py]

**Steps to Reproduce**
```python
from pycontrails.datalib.gfs import GFSForecast
from pycontrails.datalib.ecmwf import ERA5
from pycontrails.models.sac import SAC
from pycontrails.models.issr import ISSR
from pycontrails.models.pcr import PCR
from pycontrails.models.humidity_scaling import ConstantHumidityScaling
import matplotlib.pyplot as plt

# ignore pycontrails warning about ECMWF humidity scaling
import warnings
warnings.filterwarnings(message=".*humidity scaling.*", action="ignore")

# Store data files to local disk (default behavior)
times = ("2023-07-20 00:00:00")
pressure_levels = [300, 250]
variables = ["t", "q"]
gfs = GFSForecast(time=times, variables=variables, pressure_levels=pressure_levels, show_progress=True)
era5 = ERA5(time=times, variables=variables, pressure_levels=pressure_levels)

met_gfs = gfs.open_metdataset()
met_era5 = era5.open_metdataset()

# Instantiate and run model
scaling = ConstantHumidityScaling(rhi_adj=0.98)

issr1 = ISSR(met_gfs, humidity_scaling=scaling).eval()
issr2 = ISSR(met_era5, humidity_scaling=scaling).eval()
issr3 = ISSR(met_gfs).eval()
issr4 = ISSR(met_era5).eval()

sac1 = SAC(met=met_gfs).eval()
sac2 = SAC(met=met_era5).eval()

pcr1 = PCR(met=met_gfs).eval()
pcr2 = PCR(met=met_era5).eval()

fig, axes = plt.subplots(nrows=4, ncols=2, figsize=(12, 18))
level = 0

sac1.data.isel(time=0, level=level).plot(x="longitude", y="latitude", ax=axes[0,0], cmap="Reds", vmin=0, vmax=1, add_colorbar=False)
axes[0,0].set_title('SAC+GFS')

sac2.data.isel(time=0, level=level).plot(x="longitude", y="latitude", ax=axes[0,1], cmap="Blues", vmin=0, vmax=1, add_colorbar=False)
axes[0,1].set_title('SAC+ERA5')

issr1.data.isel(time=0, level=level).plot(x="longitude", y="latitude", ax=axes[1,0], cmap="Reds", vmin=0, vmax=1, add_colorbar=False)
axes[1,0].set_title('ISSR+GFS (With Humidity Scaling)')

issr2.data.isel(time=0, level=level).plot(x="longitude", y="latitude", ax=axes[1,1], cmap="Blues", vmin=0, vmax=1, add_colorbar=False)
axes[1,1].set_title('ISSR+ERA5 (With Humidity Scaling)')

issr3.data.isel(time=0, level=level).plot(x="longitude", y="latitude", ax=axes[2,0], cmap="Reds", vmin=0, vmax=1, add_colorbar=False)
axes[2,0].set_title('ISSR+GFS (No Humidity Scaling)')

issr4.data.isel(time=0, level=level).plot(x="longitude", y="latitude", ax=axes[2,1], cmap="Blues", vmin=0, vmax=1, add_colorbar=False)
axes[2,1].set_title('ISSR+ERA5 (No Humidity Scaling)')

pcr1.data.isel(time=0, level=level).plot(x="longitude", y="latitude", ax=axes[3,0], cmap="Reds", vmin=0, vmax=1, add_colorbar=False)
axes[3,0].set_title('PCR+GFS')

pcr2.data.isel(time=0, level=level).plot(x="longitude", y="latitude", ax=axes[3,1], cmap="Blues", vmin=0, vmax=1, add_colorbar=False)
axes[3,1].set_title('PCR+ERA5')

plt.tight_layout()
plt.show()
```
![image](https://github.com/contrailcirrus/pycontrails/assets/133058544/4a8f72b3-bff2-4e7d-b7d1-e13776b06cd3)

**Comment by zebengberg** [comment]
Hi @Cybis320 

Thanks for giving such a clear example. I'm able to reproduce what you're seeing.

I believe you're seeing a known limitation of the GFS model: it's inability to forecast ice supersaturation. My naive understanding of the GFS is that any ice supersaturation is assumed to undergo deposition to ice clouds, thereby driving RHi below 1. Section 3.4 of [this paper](https://repository.library.noaa.gov/view/noaa/44636/noaa_44636_DS1.pdf) goes into detail.

Consequently, the pycontrails `ISSR` or `PCR` models essentially won't give positive predictions using raw GFS data. You can see that if you calculate RHi directly. Piggybacking on your snippet, we can look at the distribution of RHi near the ISSR threshold.

```python

import numpy as np
from pycontrails.physics.thermo import rhi

q = met_gfs.data.specific_humidity
T = met_gfs.data.air_temperature
p = met_gfs.data.air_pressure
rhi_gfs = rhi(q, T, p)

q = met_era5.data.specific_humidity
T = met_era5.data.air_temperature
p = met_era5.data.air_pressure
rhi_era5 = rhi(q, T, p)

fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(12, 5))

bins = np.linspace(0.95, 1.05, 100)
rhi_gfs.plot.hist(bins=bins, ax=ax1)
rhi_era5.plot.hist(bins=bins, ax=ax2)

ax1.set_ylim(0, 33000)
ax2.set_ylim(0, 33000)
ax1.set_title("RHi GFS")
ax2.set_title("RHi ERA5")
```
<img width="955" alt="rhi" src="https://github.com/contrailcirrus/pycontrails/assets/38074806/142dc8d6-555f-4290-ac85-0ed3c93658db">

As you can see, the GFS-computed RHi rarely predicts ice supersaturation.


------------

The question of humidity correction is related. In Schumann's 2012 paper in which he defines the CoCiP model, he describes humidity correction as a way to account for sub-grid-scale variations in humidity. In more recent work, we often reframe humidity correction as a method to fit meteorology data to other sources of ground truth. In particular, we've done some work fitting ECMWF data to IAGOS in situ measurements. See section S3 in @roger-teoh's [North 
Atlantic paper](https://elib.dlr.de/188048/2/Teoh_ACP2022_Supplement_Schumann_Gryspeerdt_Shapiro_Molloy_Koudis_Voigt_Stettler_North_Atlantic_ACP_2022.pdf).

We haven't yet attempted this humdity correction on GFS data. In theory, it would be possible, though I don't know if the corrected RHi would be useful for anything given how the GFS model handles ice super saturation. We generally recommend using ERA5 meteorology if possible. The GFS forecasts could be useful, especially if used in conjunction with ERA5. This isn't something we've explored deeply.
