### ISSUE TITLE
Variation in EF sum - Passing flight object as a list

### ISSUE THREAD

**Issue by mlshapiro** [contrailcirrus/pycontrails#78]
### Discussed in https://github.com/contrailcirrus/pycontrails/discussions/77

<div type='discussions-op-text'>

<sup>Originally posted by **nataj27** August 14, 2023</sup>
I've been experimenting with the pycontrails using some sample waypoints. 
I observed that the sum of EF changes depending on the order in which flights are stored in the flight object list. 

For Example: If the flight object is in the following order -->Flight_object_list = [FL1_obj, FL2_obj, FL3_obj, FL4_obj] the sum of EF for each of the flights are different compared to when the Flight_object_list = [FL3_obj, FL4_obj, FL1_obj, FL2_obj]. 
 </div>

**Comment by mlshapiro** [comment]
@nataj27 Can you attach a script or notebook where you see this?

**Comment by nataj27** [comment]
Apologies, this is not a bug. I am very new to pycontrails and made the mistake of considering met and rad variables corresponding to the last flight in the flight object list. Thus, every time the order of list changed, the EF sum changed. Kindly ignore this question.

**Comment by mlshapiro** [comment]
No problem! Thanks for resolving.
